FROM 'jetbrains/teamcity-minimal-agent'

RUN curl -sL https://deb.nodesource.com/setup_8.x |  bash - 
RUN apt-get update && apt-get install git nodejs -y  
RUN npm install -g create-react-native-app yarn
RUN npm install -g npm@4.6.1
RUN yarn global add exp
