version: '2'

services:  
  server:
    image: 'jetbrains/teamcity-server' # the official JetBrains image
    volumes:
      - 'D:\Docker\teamcity\data:/data/teamcity_server/datadir'
      - 'D:\Docker\teamcity\logs:/data/teamcity/logs'
    ports:
      - 8111:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
  agent:
    build: .
    environment:
      - SERVER_URL=server:8111